[[themes]]
  name = "DarK Red"
  author = "github-username"
  description = "DucKRed DucKRed DucKRed DucKRed"
  tags = ["dark", "red", "high-contrast"]
  date = "pr-merge-date"
  [themes.style]
    alpha = 1.0
    disabledAlpha = 0.6000000238418579
    windowPadding = [8.0, 8.0]
    windowRounding = 0.0
    windowBorderSize = 1.0
    windowMinSize = [32.0, 32.0]
    windowTitleAlign = [0.5, 0.5]
    windowMenuButtonPosition = "Left"
    childRounding = 0.0
    childBorderSize = 1.0
    popupRounding = 0.0
    popupBorderSize = 1.0
    framePadding = [4.0, 3.0]
    frameRounding = 0.0
    frameBorderSize = 0.0
    itemSpacing = [8.0, 4.0]
    itemInnerSpacing = [4.0, 4.0]
    cellPadding = [4.0, 2.0]
    indentSpacing = 21.0
    columnsMinSpacing = 6.0
    scrollbarSize = 14.0
    scrollbarRounding = 0.0
    grabMinSize = 10.0
    grabRounding = 0.0
    tabRounding = 0.0
    tabBorderSize = 0.0
    tabMinWidthForCloseButton = 0.0
    colorButtonPosition = "Right"
    buttonTextAlign = [0.5, 0.5]
    selectableTextAlign = [0.0, 0.0]
  [themes.style.colors]
    Text = "rgba(255, 255, 255, 1.0)"
    TextDisabled = "rgba(127, 127, 127, 1.0)"
    WindowBg = "rgba(10, 10, 10, 1.0)"
    ChildBg = "rgba(14, 14, 14, 1.0)"
    PopupBg = "rgba(0, 0, 0, 1.0)"
    Border = "rgba(255, 0, 0, 1.0)"
    BorderShadow = "rgba(0, 0, 0, 1.0)"
    FrameBg = "rgba(30, 30, 30, 1.0)"
    FrameBgHovered = "rgba(255, 0, 0, 0.5647059082984924)"
    FrameBgActive = "rgba(255, 0, 0, 0.5647059082984924)"
    TitleBg = "rgba(0, 0, 0, 1.0)"
    TitleBgActive = "rgba(10, 10, 10, 1.0)"
    TitleBgCollapsed = "rgba(0, 0, 0, 0.0)"
    MenuBarBg = "rgba(20, 20, 20, 0.9411764740943909)"
    ScrollbarBg = "rgba(255, 0, 0, 0.5647059082984924)"
    ScrollbarGrab = "rgba(255, 0, 0, 0.501960813999176)"
    ScrollbarGrabHovered = "rgba(255, 0, 0, 1.0)"
    ScrollbarGrabActive = "rgba(255, 0, 0, 1.0)"
    CheckMark = "rgba(255, 0, 0, 1.0)"
    SliderGrab = "rgba(255, 0, 0, 0.8154506683349609)"
    SliderGrabActive = "rgba(255, 0, 0, 0.8156862854957581)"
    Button = "rgba(255, 0, 0, 0.501960813999176)"
    ButtonHovered = "rgba(255, 0, 0, 0.7450980544090271)"
    ButtonActive = "rgba(255, 0, 0, 1.0)"
    Header = "rgba(255, 0, 0, 0.6566523313522339)"
    HeaderHovered = "rgba(255, 0, 0, 0.8039215803146362)"
    HeaderActive = "rgba(255, 0, 0, 1.0)"
    Separator = "rgba(20, 20, 20, 0.501960813999176)"
    SeparatorHovered = "rgba(20, 20, 20, 0.6695278882980347)"
    SeparatorActive = "rgba(20, 20, 20, 0.9570815563201904)"
    ResizeGrip = "rgba(26, 29, 33, 0.2000000029802322)"
    ResizeGripHovered = "rgba(52, 53, 55, 0.2000000029802322)"
    ResizeGripActive = "rgba(77, 77, 77, 0.2000000029802322)"
    Tab = "rgba(255, 0, 0, 0.4392156898975372)"
    TabHovered = "rgba(255, 0, 0, 1.0)"
    TabActive = "rgba(255, 0, 0, 1.0)"
    TabUnfocused = "rgba(17, 17, 17, 0.9725490212440491)"
    TabUnfocusedActive = "rgba(17, 17, 17, 1.0)"
    PlotLines = "rgba(155, 155, 155, 1.0)"
    PlotLinesHovered = "rgba(242, 88, 88, 1.0)"
    PlotHistogram = "rgba(242, 88, 88, 1.0)"
    PlotHistogramHovered = "rgba(109, 92, 92, 1.0)"
    TableHeaderBg = "rgba(255, 0, 0, 0.7124463319778442)"
    TableBorderStrong = "rgba(255, 0, 0, 1.0)"
    TableBorderLight = "rgba(255, 0, 0, 1.0)"
    TableRowBg = "rgba(0, 0, 0, 1.0)"
    TableRowBgAlt = "rgba(50, 50, 50, 0.6274510025978088)"
    TextSelectedBg = "rgba(255, 0, 0, 1.0)"
    DragDropTarget = "rgba(66, 69, 97, 1.0)"
    NavHighlight = "rgba(46, 58, 71, 1.0)"
    NavWindowingHighlight = "rgba(255, 255, 255, 0.699999988079071)"
    NavWindowingDimBg = "rgba(204, 204, 204, 0.2000000029802322)"
    ModalWindowDimBg = "rgba(204, 204, 204, 0.3499999940395355)"
